In [1]:
import pandas as pd
import numpy as np
import datetime as dt
from pathlib import Path
from yahoofinancials import YahooFinancials
import matplotlib.pyplot as plt
from iexfinance.stocks import get_historical_data
import seaborn as sns

In [6]:
Tickers=['MRNA', 'GILD', 'REGN', 'DVAX', 'CYDY','JNJ', 'INO', 'VXRT', 'TBIO', 'GSK']
i=0

for x in Tickers:
    file_in=Path('./data/'+x+'.csv')
                                                 
    if i ==0:
        my_port_df= pd.read_csv(file_in,index_col='Date', parse_dates=True, infer_datetime_format=True)
        i+=1
    else:
        df= pd.read_csv(file_in,index_col='Date', parse_dates=True, infer_datetime_format=True)
        my_port_df=my_port_df.join(df)
        
my_port_df

,MRNA,GILD,REGN,DVAX,CYDY,JNJ,INO,VXRT,TBIO,GSK
Date,,,,,,,,,,
2018-12-07,18.600000,64.476410,372.829987,10.54,0.58,140.546616,5.16,3.00,8.53,35.039848
2018-12-10,18.799999,63.852001,377.589996,10.87,0.57,140.382324,5.19,2.76,8.51,35.396828
2018-12-11,18.010000,64.069588,375.720001,10.82,0.54,141.580704,5.19,2.70,9.06,35.096214
2018-12-12,18.680000,64.466957,377.959991,11.64,0.54,142.160538,5.31,2.75,9.00,35.396828
2018-12-13,18.760000,64.257065,378.510010,10.49,0.52,142.875671,5.10,2.68,8.73,35.641071
...,...,...,...,...,...,...,...,...,...,...
2020-03-30,30.480000,75.930000,473.000000,3.56,2.61,133.009995,8.02,1.70,11.48,37.599998
2020-03-31,29.950001,74.760002,488.290009,3.53,2.67,131.130005,7.44,1.77,9.97,37.889999
2020-04-01,29.670000,72.510002,496.649994,3.28,3.07,128.809998,7.70,1.73,8.33,37.220001
2020-04-02,33.200001,76.980003,498.750000,3.46,2.35,133.149994,7.52,1.68,9.09,37.700001
2020-04-03,34.840000,78.209999,493.320007,3.17,2.79,134.169998,7.74,1.70,9.53,37.139999